### ISSUE TITLE
Validate that number of permissions and rationales passed to PermissionsPager#showPermissionsPager is equal

### ISSUE THREAD

**Issue by benwicks** [BradPatras/PermissionsPager#1]
It's currently possible to pass any String[] of any size for the first 2 parameters to PermissionsPager#showPermissionsPager.

Can you add a way to validate that the number of permissions and rationales is the same?

**Comment by BradPatras** [comment]
Good point, the loading of the permissions and rationales wasn't thought out very well. I've redone the PermissionsPager construction flow, take a look.

``` 
PermissionsPager.buildPermissionsPager(this)
                .with(Manifest.permission.ACCESS_FINE_LOCATION, "We need to see where u at")
                .and(Manifest.permission.WRITE_EXTERNAL_STORAGE, "Maybe this is a file explorer")
                .and(Manifest.permission.READ_CALENDAR, "Or maybe this is a calendar app")
                .show();
```
The previous method of showing the pager is now deprecated. (as of commit 6225d07)
